#!/bin/sh

############################################################
#  Program:
#  Author :
############################################################


## BEGIN SCRIPT
usage()
{
    cat << EOF

usage: $0 OPTIONS

version: 0.2

OPTIONS can be:
  -h  Show this message
  -m  mem      Memory (default 3g)
  -t  threads  Threads per device (default 1)
  -d  devices  Number of devices (default 1) or device names
  -n  name     Name (default quick_q)
  -c  cmd      Command
  -q  queue    Queue name
  -W  attr     Additional attributes
EOF
}

# Show usage when there are no arguments.
if test -z "$1"
then
    usage
    exit
fi

MEM="4g"
NAME="quick_q"
THREADS=1
DEVICE=1
CMD=1
QUEUE=
ATTRS=
NODES=

# Check options passed in.
while getopts "h m:t:n:c:d:q:l:W:" OPTION
do
    case $OPTION in
        h)
            usage
            exit 1
            ;;
        m)
            MEM=$OPTARG
            ;;
        t)
            THREADS=$OPTARG
            ;;
        d)
            DEVICE=$OPTARG
            ;;
        n)
            NAME=$OPTARG
            ;;
        c)
            CMD=$OPTARG
            ;;
        q)
            QUEUE=$OPTARG
            ;;
        W)
            ATTRS=$OPTARG
            ;;
        ?)
            usage
            exit
            ;;
    esac
done

#QSUB="/usr/pbs/bin/qsub"
QSUB=qsub

# for pbs_version = PBSPro_11.2.0.113417
#QSUB_CMD="$QSUB -l select=$DEVICE:mem=$MEM:ncpus=$THREADS -m bae -N $NAME -M rl6sf@virginia.edu"
# for version: 3.0.3
QSUB_CMD="$QSUB -l nodes=$DEVICE:ppn=$THREADS,mem=$MEM -m abe -N $NAME"

if [ ! -z $QUEUE ]
then
	QSUB_CMD="$QSUB_CMD -q $QUEUE"
fi

if [ ! -z $ATTRS ]
then
	QSUB_CMD="$QSUB_CMD -W $ATTRS"
fi


#echo $QSUB_CMD

JID=`echo "cd \\$PBS_O_WORKDIR; $CMD" | $QSUB_CMD`
echo $JID
DATE=`date +%Y%m%d_%T`
echo $DATE > $JID.log
echo $JID >> $JID.log
echo $CMD >> $JID.log
