#!/usr/bin/env python

import random
from optparse import OptionParser

parser = OptionParser()

parser.add_option("-s",
                  "--sequence",
                  dest="sequence",
                  help="Sequence not given")

parser.add_option("-k",
                  "--kmer",
                  dest="k",
                  type="int",
                  help="Kmer size not given")

parser.add_option("-d",
                  "--dups",
                  action="store_true",
                  dest="d",
                  default=False,
                  help="Print only duplicates")

parser.add_option("-c",
                  "--count",
                  action="store_true",
                  dest="count",
                  default=False,
                  help="Print kmer counts")

(options, args) = parser.parse_args()


if not options.sequence:
    parser.error('Sequence not given')

if not options.k:
    parser.error('K not given')

C={}
K=[]
D={}
for i in range(len(options.sequence) - options.k + 1):
    kmer = options.sequence[i:(i+options.k)]
    if options.count:
        if not kmer in C:
            C[kmer] = 0;
        C[kmer] += 1;
    else:
        if not kmer in K:
            K.append(kmer)
        else:
            if kmer not in D:
                D[kmer]=0
            D[kmer]+=1

if options.count:
    for c in C:
        print c + "\t" + str(C[c])
elif options.d:
    for d in D:
        print d + "\t" + str(D[d])
else:
    for k in K:
        print k
